### ISSUE TITLE
Please create an official lifx-npm module

### ISSUE THREAD

**Issue by suhajdab** [LIFX/LIFX-customer-suggestions#14]

**Comment by ryanj** [comment]
+1  I'd be happy to help if you can give me some info on how to talk to the Firmware2.0 wifi build

**Comment by smarthall** [comment]
LIFX will not be creating a lifx-npm module. Instead we have released the documentation describing how our [HTTP Remote Control API](http://api.developer.lifx.com/) and our [LAN protocols](http://lan.developer.lifx.com/) work. We hope this will enable developers to build more varied and better SDKs than we could have done alone.

@ryanj You can find the 2.0 LAN Protocol documentation here: http://lan.developer.lifx.com/ and support for it is available here: http://community.lifx.com/
