### ISSUE TITLE
Some customer communication?

### ISSUE THREAD

**Issue by ThomasWrobel** [LIFX/LIFX-customer-suggestions#15]
Anything really? Is LIFX deliberately ignoring developers these days :? Have they decided they dont want a app ecosystem for their bulbs after all?

**Comment by dotMorten** [comment]
I thought that too, but lately they are quite responsive in the protocol repo. It's nice to see they are coming back online again (finally)

**Comment by smarthall** [comment]
The best place to reach us currently is by dropping by our newly launched [Developer Zone](https://community.lifx.com/). I can assure you that we are taking the concerns of our third party developers seriously.
